Refactoring tests: unify assertion of TrackPoints
OpenTracksApp/OpenTracks pull request #851
Opened 2021-06-27 19:09 UTC by dennisguse

The assertions of TrackPoints was implemented several times and done differently.
This makes testing complicated and thus should be improved.

Wait for #848 and then rebase.

2021-06-28 21:12 UTC, dennisguse commented
After merging #848; rebased onto main.
* [ ] Speed is not yet verified (expectation needs to be set)
* [ ] Refactor `TrackPointAssert.expect()` to use TrackPoint constructor directly
* [ ] Check GPX test failure

2021-07-01 21:21 UTC, rgmf commented on src/main/java/de/dennisguse/opentracks/viewmodels/IntervalStatistics.java
> +            if (gain_m != null && lastTrackPoint != null && lastTrackPoint.hasAltitudeGain()) {
We have `hasGain` method, why not use it?

```if (hasGain() && lastTrackPoint != null && lastTrackPoint.hasAltitudeGain())```?

2021-07-01 21:36 UTC, rgmf reviewed
I think there's a little bug: gain and loss are always unknown "-" (in both track recording layout and intervals fragment).

2021-07-02 05:41 UTC, dennisguse commented
@rgmf Thanks - I will check this today!
And I am so happy that the tests are finally working again!

2021-07-02 19:57 UTC, dennisguse commented
@rgmf I even did a `=` instead of  `+=`....
Now it's working: after first pressure measurement 0m is shown and gain/loss is updated via temporary TrackStatistics every second.
Now, we can test in an elevator (what I did)...

2021-07-03 11:02 UTC, dennisguse commented
@rgmf I should stop working on this PR - it just gets really big.
I just wanted to refactor the tests... :sun_with_face:

2021-07-03 21:02 UTC, rgmf requested changes
👍

2021-07-04 06:33 UTC, dennisguse commented
@rgmf I am slightly confused - what needs to be changed?

2021-07-04 09:20 UTC, rgmf commented
> @rgmf I am slightly confused - what needs to be changed?

If gain/loss unknown issue is fixed then it's ready for me ;)

2021-07-04 09:51 UTC, rgmf approved these changes

2021-07-04 14:53 UTC, merged